### ISSUE TITLE
[EPIC] too many memory allocations in tx execution

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/ethermint#429]
__Proposal:__ reduce memory allocations in tx execution

__Current behavior:__

When benchmark parallel EVM execution, memory allocation, and GC seem becoming a bottleneck.

And there are indeed many unnecessary allocations in both SDK and ethermint

__Desired behavior:__

Pick some low hanging fruits first:
- big int and legacy decimals
- unnecessary conversions between different representations (protobuf <-> go-ethereum).

__Use case:__ [Why is this important (helps with prioritizing requests)]

Requests may be closed if we're not actively planning to work on them.

## Tracking

- [x] #454
- [x] #471
- [ ] avoid gas kv construction, we don't need gaskv in eth tx execution
- [x] #469
- [ ] reduce duplicated `GetAccount` calls
- [ ] reduce big.Int copy during bank operations
