### ISSUE TITLE
[EPIC] block-stm integration

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/ethermint#432]
- [x] https://github.com/crypto-org-chain/cosmos-sdk/pull/206
- [x] https://github.com/crypto-org-chain/ethermint/pull/447
- [x] https://github.com/crypto-org-chain/ethermint/pull/448
- [x] https://github.com/crypto-org-chain/go-block-stm/pull/5
- [ ] Optimize `Has` operation in go-block-stm
- [x] https://github.com/crypto-org-chain/ethermint/pull/456
- [x] https://github.com/crypto-org-chain/ethermint/pull/450
